version: '3'
services:
  mongo:
    container_name: testing-mongo
    image: mongo:7.0
    environment:
      - MONGODB_SMALL_FILES=true
      - MONGODB_DISABLE_BACKGROUND_WRITES=true
    ports:
       - 27017:27017
    command: "mongod"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet localhost/test --eval 'db.runCommand({ ping: 1 }).ok ? process.exit(0) : process.exit(1)'"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes: 
      - ~/mongo/data:/data/db

  api:
    container_name: testing-api
    build: .
    env_file: 
      - .ci.env
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
